### ISSUE TITLE
Problem on safari using nuxt

### ISSUE THREAD

**Issue by shutt** [Akryum/vue-observe-visibility#36] opened 2018-10-17 09:20 UTC
I'm using this on a nuxt project and i'm not able to make it work on safari or mobile (ios) does anyone was able to set it up correctly on nuxt?

**Comment by manniL** [comment] 2018-10-21 01:13
duplicate of https://github.com/Akryum/vue-observe-visibility/issues/26

**Comment by toleberdyyeva** [comment] 2019-02-04 03:10
Does anyone solved this problem ? Cause I'm using it in nuxt project , And error still occurs.

**Comment by Akryum** [comment] 2019-05-06 16:44
Duplicate of #26

**Closed by Akryum** 2019-05-06 16:44 UTC
